version: '3.8'

services:
  # Backend API (FastAPI)
  api:
    build: ./backend
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - USE_SQLITE=True
      - DATABASE_URL=sqlite:///./data/expense_tracker.db
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend (Next.js)
  web:
    command: sh -c "npm run build && npm start"
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

volumes:
  sqlite_data: 