services:
  # Backend API Service
  - type: web
    name: expense-tracker-api
    env: python
    buildCommand: cd backend && chmod +x render-build.sh && ./render-build.sh
    startCommand: cd backend && python verify_db.py && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEBUG
        value: false
      - key: USE_SQLITE
        value: true  # Using SQLite for simplicity
      - key: SECRET_KEY
        generateValue: true  # Generate a secure random value
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: FRONTEND_URL
        value: https://expense-tracker-frontend.onrender.com  # Update with your frontend URL

  # Frontend Web Service
  - type: web
    name: expense-tracker-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && node render-start.js
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://expense-tracker-api.onrender.com  # Update with your backend URL

# We don't need a database service since we're using SQLite 