services:
  # Backend API Service
  - type: web
    name: expense-tracker-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEBUG
        value: false
      - key: USE_SQLITE
        value: false  # Use PostgreSQL in production
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true  # Generate a secure random value
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: FRONTEND_URL
        value: https://expense-tracker-frontend.onrender.com  # Update with your frontend URL

  # Frontend Web Service
  - type: web
    name: expense-tracker-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://expense-tracker-api.onrender.com  # Update with your backend URL

# Database
databases:
  - name: expense-tracker-db
    databaseName: expense_tracker
    plan: free  # Or choose a paid plan for production 